### ISSUE TITLE
pypi源过期

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#126]
@knight42 

```
============ SYNC STARTED AT 2017-04-29 12:48:01 ============
Traceback (most recent call last):
  File "/usr/bin/bandersnatch", line 11, in <module>
    load_entry_point('bandersnatch==2.0.0', 'console_scripts', 'bandersnatch')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/bandersnatch/main.py", line 4, in <module>
    import bandersnatch.mirror
  File "/usr/lib/python2.7/site-packages/bandersnatch/mirror.py", line 1, in <module>
    from .package import Package
  File "/usr/lib/python2.7/site-packages/bandersnatch/package.py", line 4, in <module>
    from urllib.parse import urlparse, unquote
ImportError: No module named parse
============ SYNC FINISHED AT 2017-04-29 12:48:07 ============
```

**Comment by knight42** [comment]
@gaoyifan urllib.parse 这个 module 只在 python3 有，看来需要装 python3

**Comment by gaoyifan** [comment]
看来bandersnatch也要抛弃python2了.....

**Comment by knight42** [comment]
Fixed by https://github.com/ustclug/ustcmirror-images/commit/497761735fce24fe2432bbc60219fe67dbc2afea
