### ISSUE TITLE
ustcmirror daemon不正常

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#161]
status页面不工作，yuki命令执行失败：

```
{ Error
    at ClientRequest.<anonymous> (/home/knight/Yuki/packages/yuki-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1295:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://localhost:9999/api/v1/repositories/anaconda failed, reason: connect ECONNREFUSED 127.0.0.1:9999',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

**Comment by knight42** [comment]
@gaoyifan 已重启，故障原因待调查

**Comment by gaoyifan** [comment]
今天早些时候daemon再次故障，刚才看，似乎是恢复了。有查到什么线索吗？ @knight42

**Comment by knight42** [comment]
导致进程直接退出的原因是触发了 EPIPE。由于现在日志已经改为写入本地文件了，我觉得最有可能的原因是客户端执行了 `ct-logs -f <repo>` 然后过早终止了。感觉这不是一个大问题，所以我现在直接忽略了 EPIPE: https://github.com/knight42/Yuki/commit/af72c50479dc9df9bd4806bdab618c85c4edfaef .

经过一段时间的观察，未发现有不良影响。
