### ISSUE TITLE
homebrew-bottles 同步失败

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#232]
```
============ SYNC STARTED AT 2018-08-22 05:55:04 ============
*********** 8< ***********
> update package info...
Initialized empty Git repository in /root/.linuxbrew/Library/Taps/homebrew/homebrew-core/.git/
From git://github.com/homebrew/homebrew-core
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
HEAD is now at f872dd9 libxml++: update 2.40.1 bottle.
> RUN brew bottle-mirror...
curl: (22) The requested URL returned error: 404 Not Found
Error: wrong number of arguments (given 1, expected 2)
/root/.linuxbrew/Library/Homebrew/exceptions.rb:538:in `block in initialize'
/root/.linuxbrew/Library/Homebrew/exceptions.rb:547:in `map'
/root/.linuxbrew/Library/Homebrew/exceptions.rb:547:in `initialize'
/root/.linuxbrew/Library/Homebrew/system_command.rb:101:in `new'
/root/.linuxbrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/root/.linuxbrew/Library/Homebrew/system_command.rb:46:in `run!'
/root/.linuxbrew/Library/Homebrew/system_command.rb:23:in `run'
/root/.linuxbrew/Library/Homebrew/system_command.rb:27:in `run!'
/root/.linuxbrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/root/.linuxbrew/Library/Homebrew/utils/curl.rb:43:in `curl'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:37:in `block (2 levels) in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:16:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:16:in `block in <top (required)>'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `each'
/root/.linuxbrew/Library/Taps/gaoyifan/homebrew-bottle-mirror/cmd/brew-bottle-mirror.rb:3:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/root/.linuxbrew/Library/Homebrew/utils.rb:18:in `require?'
/root/.linuxbrew/Library/Homebrew/brew.rb:93:in `<main>'
============ SYNC FINISHED AT 2018-08-22 05:55:14 ============
```

**Comment by gaoyifan** [comment]
经查，由于homebrew上游修改了API的行为，导致同步程序生成了错误的文件名，下载过程出现404错误。
上游PR：https://github.com/Homebrew/brew/pull/4612

已对同步程序进行相应的调整。
