### ISSUE TITLE
Julia 镜像错误

### ISSUE THREAD

**Issue by sunoru** [ustclug/discussions#253]
线上的 Julia 镜像似乎在本地克隆 Metadata 的那一步 fail 了导致 registries 和 packages 都没同步，有人能检查一下出了什么问题吗？

https://mirrors.ustc.edu.cn/julia/status.json 里写着 metadata 同步失败

https://mirrors.ustc.edu.cn/julia/metadata/METADATA.jl/ 是空的

**Comment by sunoru** [comment]
这次看上去是卡在了同步 releases 的这一步。。https://mirrors.ustc.edu.cn/julia/status.json 显示 releases 的 "status": "synchronizing"

不太应该卡在这里的才对..能检查一下么？

**Comment by gaoyifan** [comment]
@sunoru  日志中提供的信息很有限：

```
============ SYNC STARTED AT 2018-11-09 09:20:42 ============
*********** 8< ***********
fatal: Not a git repository (or any of the parent directories): .git
```
（目前同步程序还在运行中）

**Comment by sunoru** [comment]
噗又 failed 了，想看看错误信息..

**Comment by gaoyifan** [comment]
@sunoru  更新同步程序后，有了新的错误信息：
```
============ SYNC STARTED AT 2018-11-10 17:12:34 ============
*********** 8< ***********
fatal: Not a git repository (or any of the parent directories): .git
[2018-11-10 17:15:02]ERROR:Failed to download https://julialangnightlies-s3.julialang.org/bin/linux/x86/julia-latest-linux32.tar.gz
[2018-11-10 17:15:02]ERROR:HTTP Error 503: first byte timeout
Aborted
============ SYNC FINISHED AT 2018-11-11 14:59:44 ============
============ SYNC STARTED AT 2018-11-11 23:43:00 ============
*********** 8< ***********
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[2018-11-12 05:25:21]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/c642d54788b3afef4cdeae13b0fd698b61cda686
[2018-11-12 05:25:21]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:25:21]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/6197f78c4142d3dc65812f30cfe707f085158e6b
[2018-11-12 05:25:21]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:25:21]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/0c36b64ba948495e119895c9f3600f00a839b2dd
[2018-11-12 05:25:21]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:25:21]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/b522bf14f18d25e74edf2012d2036e12942c6a47
[2018-11-12 05:25:21]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:25:22]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/997f13fa4ee9b770d78a0ddd0298f114af379330
[2018-11-12 05:25:22]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:25:22]ERROR:Failed to download https://api.github.com/repos/rennis250/GLUT.jl/tarball/c1a73356f1a2aedfb8fdb60b7df86ce40c15955b
[2018-11-12 05:25:22]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:26:28]ERROR:Failed to download https://api.github.com/repos/rennis250/GetC.jl/tarball/c5c8807f77e289fbb3344200631384d500d1e20a
[2018-11-12 05:26:28]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:26:28]ERROR:Failed to download https://api.github.com/repos/rennis250/GetC.jl/tarball/b77a05a0e4c889d4e5ef8288eba5826c294a33ef
[2018-11-12 05:26:28]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:26:28]ERROR:Failed to download https://api.github.com/repos/rennis250/GetC.jl/tarball/a53a641096def0fb2f8d45dd94db399b22a857a2
[2018-11-12 05:26:28]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:40:07]ERROR:Failed to download https://api.github.com/repos/bramtayl/SessionHacker.jl/tarball/39c40c04f64d151cf9a31decc26317162a22f16f
[2018-11-12 05:40:07]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:40:13]WARNING:Packages not on github are currently not supported.
[2018-11-12 05:42:13]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/4531390c290f86345688cc67161c48e09846ddbc
[2018-11-12 05:42:13]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:42:14]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/019f01faf0edef32307d2aae4e5203e30be8c1b3
[2018-11-12 05:42:14]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:42:14]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/855c642dbfd264dae9957f1697e90171bd751f44
[2018-11-12 05:42:14]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:42:14]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/80191fe422933bd21fea48c2f62b47ebbaf15bb2
[2018-11-12 05:42:14]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:42:14]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/ff442d702fda3c71564dcf4407738eaef44c7e30
[2018-11-12 05:42:14]ERROR:HTTP Error 404: Not Found
[2018-11-12 05:42:15]ERROR:Failed to download https://api.github.com/repos/rennis250/SDL.jl/tarball/47016b86b32359b1aead108548e16cb7f8698212
[2018-11-12 05:42:15]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:06:42]ERROR:Failed to download https://api.github.com/repos/rennis250/Sparrow.jl/tarball/87fe402871e46b309b81b85bb0a127e001bfc2c0
[2018-11-12 06:06:42]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:10:21]ERROR:Failed to download https://api.github.com/repos/JuliaComputing/StringArrays.jl/tarball/aa1e5bea4dcfea0ec6b6f46bdf71e418ddb72463
[2018-11-12 06:10:21]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:14:37]ERROR:Failed to download https://api.github.com/repos/rgiordan/SloanD/tarball/bb38342918c4ee3f0ab08a03a20f09e94b77be3d
[2018-11-12 06:14:37]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:14:37]ERROR:Failed to download https://api.github.com/repos/rgiordan/SloanD/tarball/6995ce1cbf4b8ed0449ce9cf30d2505235c12b67
[2018-11-12 06:14:37]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:14:37]ERROR:Failed to download https://api.github.com/repos/rgiordan/SloanD/tarball/b9673f4f302216cfef9460730d79d5cefe6836ef
[2018-11-12 06:14:37]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:14:37]ERROR:Failed to download https://api.github.com/repos/rgiordan/SloanD/tarball/ddb076477135eb34d724336e1651e360ced5caf4
[2018-11-12 06:14:37]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:14:38]ERROR:Failed to download https://api.github.com/repos/rgiordan/SloanD/tarball/e2031422af22f8ee10cd82b6f1c4028ae8d9ada0
[2018-11-12 06:14:38]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:19:06]ERROR:Failed to download https://api.github.com/repos/JuliaLinearAlgebra/SuiteSparse.jl/tarball/f8dc06de847055e5a1ea635595956f92e81af82d
[2018-11-12 06:19:06]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:47:26]ERROR:Failed to download https://api.github.com/repos/bramtayl/TypedBools.jl/tarball/65c1ad52388261c269f7b3477acdbfebdd839187
[2018-11-12 06:47:26]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:47:26]ERROR:Failed to download https://api.github.com/repos/bramtayl/TypedBools.jl/tarball/e2dd1e4343f8d8abdff7264f39513055a966b6dc
[2018-11-12 06:47:26]ERROR:HTTP Error 404: Not Found
[2018-11-12 06:47:26]ERROR:Failed to download https://api.github.com/repos/bramtayl/TypedBools.jl/tarball/5f241de0df1c8cf669dd2cf7ac2fce90cb932fdc
[2018-11-12 06:47:26]ERROR:HTTP Error 404: Not Found
[2018-11-12 07:25:27]ERROR:Failed to download https://api.github.com/repos/bramtayl/ZippedArrays.jl/tarball/ea60fddf4e576a7aa7693e13884ba681ddf0a371
[2018-11-12 07:25:27]ERROR:HTTP Error 404: Not Found
[2018-11-12 07:25:27]ERROR:Failed to download https://api.github.com/repos/bramtayl/ZippedArrays.jl/tarball/a5eff406812e3c5143fd80d5736143ca9415f553
[2018-11-12 07:25:27]ERROR:HTTP Error 404: Not Found
[2018-11-12 07:25:27]ERROR:Failed to download https://api.github.com/repos/bramtayl/ZippedArrays.jl/tarball/0f10cca0a9970e3a7153dad70d3c0d040e88a71a
[2018-11-12 07:25:27]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:09:31]ERROR:Failed to download https://api.github.com/repos/bramtayl/Parts.jl/tarball/d731c2c0b173633b6cd1b5e76ecad367d90e79db
[2018-11-12 08:09:31]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:09:32]ERROR:Failed to download https://api.github.com/repos/bramtayl/Parts.jl/tarball/fda86dbe5fafed828849416ae20f5f0862a16d0b
[2018-11-12 08:09:32]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/a75ad567cab5ad3d17d926c70fb2550a55b3ec57
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/1d6c041c3749abafddf40e9a96a190fce7f8b064
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/b09a14105a8eedaeee8441764ad01b56d603a115
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/3bace11fc10fa32662a0fd2a1ef12beed671d685
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/b8f72fbadd8de0c8298bc4e4cfbff894327c313e
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/aa2133edca8be85db6112a77bc40f26b18d1aab6
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/11eeefc470a72cb8ff1eca21cc0013652130ef1e
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:24:59]ERROR:Failed to download https://api.github.com/repos/greenflash1357/D/tarball/b21bcd92583a293b296e01f159ccc9482b72e62f
[2018-11-12 08:24:59]ERROR:HTTP Error 404: Not Found
[2018-11-12 08:34:12]ERROR:Failed to update packages
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/julia-mirror/scripts/mirror_julia.py", line 122, in download
    urllib.request.urlretrieve(url, f.name)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/julia-mirror/scripts/mirror_julia.py", line 582, in <module>
    main()
  File "/julia-mirror/scripts/mirror_julia.py", line 578, in main
    try_update('packages', update_packages, config, status)
  File "/julia-mirror/scripts/mirror_julia.py", line 562, in try_update
    raise e
  File "/julia-mirror/scripts/mirror_julia.py", line 557, in try_update
    update(config, status)
  File "/julia-mirror/scripts/mirror_julia.py", line 527, in update_packages
    update_package(config, status, package_name, registry)
  File "/julia-mirror/scripts/mirror_julia.py", line 493, in update_package
    download_all(config, current_dir, urllist)
  File "/julia-mirror/scripts/mirror_julia.py", line 260, in download_all
    for (filename, url) in urllist))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ConnectionResetError: [Errno 104] Connection reset by peer
============ SYNC FINISHED AT 2018-11-12 08:34:14 ============
```

**Comment by gaoyifan** [comment]
done
1. 为`/julia/PkgMirrors.jl.git` 开启了 git-http-backend
2. 为`/julia/PkgMirrors.jl.git` 增加了git协议的支持：git://mirrors.ustc.edu.cn/julia/PkgMirrors.jl.git
3. （隐藏临时目录 | 异常退出时，确保临时目录会被清理）：https://github.com/ustclug/ustcmirror-images/commit/52ca9e4b8fa5eb043734cf97503533a0bf17385b

**Comment by gaoyifan** [comment]
update：全站以 `.git` 结尾的目录都开启了 git-http-backend
@sunoru 请尝试看看

**Comment by sunoru** [comment]
OK, 现在应该没问题了~

**Comment by sw3196** [comment]
你好, 我在自己的服务器上想搭一个julia镜像, 想请问下nginx应该怎么配置才能给全站以 .git 结尾的目录都开启 git-http-backend 呢?

**Comment by iBug** [comment]
@sw3196 以下脚本供参考：

```nginx
location ~ \.git/(info/refs|git-upload-pack) {
    fastcgi_read_timeout 5m;
    fastcgi_pass    unix:/var/run/fcgiwrap.socket;

    fastcgi_param   SCRIPT_FILENAME     /usr/lib/git-core/git-http-backend;
    fastcgi_param   GIT_HTTP_EXPORT_ALL "";
    fastcgi_param   GIT_PROJECT_ROOT    /srv/git;
    fastcgi_param   PATH_INFO           $uri;

    include         fastcgi_params;
}
```

**Comment by sw3196** [comment]
@iBug 
非常感谢, 想再请教下 GIT_PROJECT_ROOT里,  /srv/git 具体是指向哪一层目录了? 比如是到julia根目录这一层就可以了吗(https://mirrors.ustc.edu.cn/julia/), 还是说要分别指向不同的.git文件了, 比如 /julia/registries/General.git/ 呢?

我现在遇到的问题是, 在nginx里配置以后, 在julia客户端添加registries时总是报404, 错误如下:
ERROR: failed to clone from xx/julia/registries/General.git, error: GitError(Code:ERROR, Class:Net, request failed with status code: 404)
