### ISSUE TITLE
ubuntu-ports同步失败

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/discussions#46]
```
$ ustcmirror sync ubuntu-ports
Traceback (most recent call last):
  File "/usr/local/bin/ustcmirror", line 9, in <module>
    load_entry_point('ustcmirror==0.1.0', 'console_scripts', 'ustcmirror')()
  File "/home/mirror/scripts/docker-ustcmirror/ustcmirror/__main__.py", line 364, in main
    manager.sync(get('name'))
  File "/home/mirror/scripts/docker-ustcmirror/ustcmirror/__main__.py", line 154, in sync
    raise KeyError(name)
KeyError: 'ubuntu-ports'
```

**Comment by knight42** [comment]
没问题啊... 需要以 mirror 用户执行

**Comment by gaoyifan** [comment]
last success 似乎是2016-09-28 16:35:05

**Comment by knight42** [comment]
crontab 的注释忘取消了
